
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FastSearcherAction;

	private global::Gtk.Action QuitAction;

	private global::Gtk.Action PreferencesAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Action QuitAction1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Entry search;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView filenames;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView preview;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FastSearcherAction = new global::Gtk.Action ("FastSearcherAction", global::Mono.Unix.Catalog.GetString ("FastSearcher"), null, null);
		this.FastSearcherAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("FastSearcher");
		w1.Add (this.FastSearcherAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.PreferencesAction = new global::Gtk.Action ("PreferencesAction", global::Mono.Unix.Catalog.GetString ("Preferences"), null, "gtk-preferences");
		this.PreferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
		w1.Add (this.PreferencesAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.QuitAction1 = new global::Gtk.Action ("QuitAction1", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("FastSearcher");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FastSearcherAction' action='FastSearcherAction'><menuitem name='PreferencesAction' action='PreferencesAction'/><menuitem/><menuitem name='QuitAction1' action='QuitAction1'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.search = new global::Gtk.Entry ();
		this.search.CanFocus = true;
		this.search.Name = "search";
		this.search.IsEditable = true;
		this.search.InvisibleChar = '●';
		this.vbox1.Add (this.search);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.search]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.filenames = new global::Gtk.TreeView ();
		this.filenames.CanFocus = true;
		this.filenames.Name = "filenames";
		this.filenames.EnableSearch = false;
		this.GtkScrolledWindow.Add (this.filenames);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w5.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.preview = new global::Gtk.TextView ();
		this.preview.CanFocus = true;
		this.preview.Name = "preview";
		this.GtkScrolledWindow1.Add (this.preview);
		this.vbox1.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow1]));
		w7.Position = 3;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 476;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.search.Changed += new global::System.EventHandler (this.OnFilterEntryTextChanged);
		this.search.Activated += new global::System.EventHandler (this.OnFilterEntryActivated);
		this.search.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnSearchKeyPressEvent);
		this.filenames.RowActivated += new global::Gtk.RowActivatedHandler (this.OnRowActivated);
		this.filenames.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnFilenamesKeyPressEvent);
		this.filenames.CursorChanged += new global::System.EventHandler (this.OnFilenamesCursorChanged);
		this.preview.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnPreviewKeyPressEvent);
	}
}
